/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const RiskEvent = IDL.Record({
  'id' : IDL.Text,
  'multiplier' : IDL.Float64,
  'endDate' : IDL.Int,
  'affectedZIPs' : IDL.Vec(IDL.Text),
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'startDate' : IDL.Int,
  'fileUrl' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Helper = IDL.Record({
  'id' : IDL.Text,
  'zip' : IDL.Text,
  'consent' : IDL.Bool,
  'note' : IDL.Text,
  'createdAt' : IDL.Int,
  'email' : IDL.Text,
  'helpType' : IDL.Text,
  'phone' : IDL.Text,
  'lastName' : IDL.Text,
  'firstName' : IDL.Text,
});
export const ProviderStatus = IDL.Variant({
  'Live' : IDL.Null,
  'Offline' : IDL.Null,
  'Unknown' : IDL.Null,
});
export const ProviderWithStatus = IDL.Record({
  'id' : IDL.Text,
  'lat' : IDL.Float64,
  'lng' : IDL.Float64,
  'status' : ProviderStatus,
  'reputationScore' : IDL.Nat,
  'inventory' : IDL.Text,
  'name' : IDL.Text,
  'isLive' : IDL.Bool,
  'lastVerified' : IDL.Int,
  'is_verified' : IDL.Bool,
  'providerType' : IDL.Text,
  'is_active' : IDL.Bool,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const CanisterStateSummary = IDL.Record({
  'active_providers' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat, IDL.Bool)),
  'total_active_providers' : IDL.Nat,
  'high_risk_window_active' : IDL.Bool,
});
export const PredictionEngineState = IDL.Record({
  'avgDailyHandoffCount' : IDL.Nat,
  'potencyToggle' : IDL.Bool,
  'sensitivitySlider' : IDL.Nat,
  'weatherToggle' : IDL.Bool,
  'simulationEnabled' : IDL.Bool,
  'stressToggle' : IDL.Bool,
  'paydayToggle' : IDL.Bool,
});
export const TouchpointRecord = IDL.Record({
  'touchpoints' : IDL.Nat,
  'agentId' : IDL.Text,
  'totalSaved' : IDL.Float64,
  'isStabilized' : IDL.Bool,
});
export const RiskPacket = IDL.Record({
  'status' : IDL.Bool,
  'data_source' : IDL.Text,
  'last_update_time' : IDL.Nat,
  'provider_id' : IDL.Text,
  'risk_score' : IDL.Nat,
});
export const VerifyResult = IDL.Variant({
  'Ok' : IDL.Text,
  'NotFound' : IDL.Null,
  'Expired' : IDL.Null,
  'AlreadyUsed' : IDL.Null,
});

export const idlService = IDL.Service({
  '_initializeAccessControl' : IDL.Func([], [], []),
  'addRiskEvent' : IDL.Func([RiskEvent], [IDL.Text], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'generateHandoffToken' : IDL.Func([IDL.Text], [IDL.Text], []),
  'getAllHelpers' : IDL.Func([], [IDL.Vec(Helper)], ['query']),
  'getAllProviders' : IDL.Func([], [IDL.Vec(ProviderWithStatus)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCanisterState' : IDL.Func([], [CanisterStateSummary], ['query']),
  'getCostPlusReferralCount' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
  'getEmergencyActive' : IDL.Func([], [IDL.Vec(ProviderWithStatus)], ['query']),
  'getEmergencyBridgeStatus' : IDL.Func(
      [],
      [
        IDL.Record({
          'activatedAt' : IDL.Int,
          'activatedBy' : IDL.Text,
          'isActive' : IDL.Bool,
        }),
      ],
      ['query'],
    ),
  'getFiscalData' : IDL.Func(
      [],
      [
        IDL.Record({
          'communityReinvestmentFund' : IDL.Float64,
          'stabilityPipelinePercent' : IDL.Float64,
          'livesSaved' : IDL.Float64,
          'stabilizedAgents' : IDL.Nat,
          'touchpointCount' : IDL.Nat,
          'dollarsSaved' : IDL.Float64,
        }),
      ],
      ['query'],
    ),
  'getHandoffCountsByZip' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat))],
      ['query'],
    ),
  'getMarketplaceGeoJSON' : IDL.Func([], [IDL.Text], ['query']),
  'getPredictionEngineState' : IDL.Func([], [PredictionEngineState], ['query']),
  'getRiskEvents' : IDL.Func([], [IDL.Vec(RiskEvent)], ['query']),
  'getSocialStressBaseline' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Float64))],
      [],
    ),
  'getTotalCostPlusReferrals' : IDL.Func([], [IDL.Nat], ['query']),
  'getTotalHandoffs' : IDL.Func([], [IDL.Nat], ['query']),
  'getTouchpointData' : IDL.Func([], [IDL.Vec(TouchpointRecord)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getWeatherAlerts' : IDL.Func([], [IDL.Text], []),
  'getWeatherRisk' : IDL.Func([], [IDL.Float64], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'receiveRiskPacket' : IDL.Func([RiskPacket], [], []),
  'recordCostPlusReferral' : IDL.Func([IDL.Text], [], []),
  'recordTouchpoint' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'registerHelper' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Bool,
        IDL.Text,
      ],
      [],
      [],
    ),
  'registerProvider' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Float64, IDL.Float64, IDL.Text],
      [],
      [],
    ),
  'removeRiskEvent' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'resetFiscalData' : IDL.Func([], [], []),
  'runHeartbeat' : IDL.Func([], [IDL.Vec(IDL.Text)], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setEmergencyActive' : IDL.Func([IDL.Bool], [], []),
  'setPredictionEngineState' : IDL.Func([PredictionEngineState], [], []),
  'setProviderActiveStatus' : IDL.Func([IDL.Text, IDL.Bool], [], []),
  'toggleLive' : IDL.Func([IDL.Text, IDL.Bool], [], []),
  'updateInventory' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'updateRiskEvent' : IDL.Func([IDL.Text, RiskEvent], [IDL.Bool], []),
  'verifyHandoff' : IDL.Func([IDL.Text], [VerifyResult], []),
  'verifyProvider' : IDL.Func([IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const RiskEvent = IDL.Record({
    'id' : IDL.Text,
    'multiplier' : IDL.Float64,
    'endDate' : IDL.Int,
    'affectedZIPs' : IDL.Vec(IDL.Text),
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'startDate' : IDL.Int,
    'fileUrl' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Helper = IDL.Record({
    'id' : IDL.Text,
    'zip' : IDL.Text,
    'consent' : IDL.Bool,
    'note' : IDL.Text,
    'createdAt' : IDL.Int,
    'email' : IDL.Text,
    'helpType' : IDL.Text,
    'phone' : IDL.Text,
    'lastName' : IDL.Text,
    'firstName' : IDL.Text,
  });
  const ProviderStatus = IDL.Variant({
    'Live' : IDL.Null,
    'Offline' : IDL.Null,
    'Unknown' : IDL.Null,
  });
  const ProviderWithStatus = IDL.Record({
    'id' : IDL.Text,
    'lat' : IDL.Float64,
    'lng' : IDL.Float64,
    'status' : ProviderStatus,
    'reputationScore' : IDL.Nat,
    'inventory' : IDL.Text,
    'name' : IDL.Text,
    'isLive' : IDL.Bool,
    'lastVerified' : IDL.Int,
    'is_verified' : IDL.Bool,
    'providerType' : IDL.Text,
    'is_active' : IDL.Bool,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const CanisterStateSummary = IDL.Record({
    'active_providers' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat, IDL.Bool)),
    'total_active_providers' : IDL.Nat,
    'high_risk_window_active' : IDL.Bool,
  });
  const PredictionEngineState = IDL.Record({
    'avgDailyHandoffCount' : IDL.Nat,
    'potencyToggle' : IDL.Bool,
    'sensitivitySlider' : IDL.Nat,
    'weatherToggle' : IDL.Bool,
    'simulationEnabled' : IDL.Bool,
    'stressToggle' : IDL.Bool,
    'paydayToggle' : IDL.Bool,
  });
  const TouchpointRecord = IDL.Record({
    'touchpoints' : IDL.Nat,
    'agentId' : IDL.Text,
    'totalSaved' : IDL.Float64,
    'isStabilized' : IDL.Bool,
  });
  const RiskPacket = IDL.Record({
    'status' : IDL.Bool,
    'data_source' : IDL.Text,
    'last_update_time' : IDL.Nat,
    'provider_id' : IDL.Text,
    'risk_score' : IDL.Nat,
  });
  const VerifyResult = IDL.Variant({
    'Ok' : IDL.Text,
    'NotFound' : IDL.Null,
    'Expired' : IDL.Null,
    'AlreadyUsed' : IDL.Null,
  });
  
  return IDL.Service({
    '_initializeAccessControl' : IDL.Func([], [], []),
    'addRiskEvent' : IDL.Func([RiskEvent], [IDL.Text], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'generateHandoffToken' : IDL.Func([IDL.Text], [IDL.Text], []),
    'getAllHelpers' : IDL.Func([], [IDL.Vec(Helper)], ['query']),
    'getAllProviders' : IDL.Func([], [IDL.Vec(ProviderWithStatus)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCanisterState' : IDL.Func([], [CanisterStateSummary], ['query']),
    'getCostPlusReferralCount' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
    'getEmergencyActive' : IDL.Func(
        [],
        [IDL.Vec(ProviderWithStatus)],
        ['query'],
      ),
    'getEmergencyBridgeStatus' : IDL.Func(
        [],
        [
          IDL.Record({
            'activatedAt' : IDL.Int,
            'activatedBy' : IDL.Text,
            'isActive' : IDL.Bool,
          }),
        ],
        ['query'],
      ),
    'getFiscalData' : IDL.Func(
        [],
        [
          IDL.Record({
            'communityReinvestmentFund' : IDL.Float64,
            'stabilityPipelinePercent' : IDL.Float64,
            'livesSaved' : IDL.Float64,
            'stabilizedAgents' : IDL.Nat,
            'touchpointCount' : IDL.Nat,
            'dollarsSaved' : IDL.Float64,
          }),
        ],
        ['query'],
      ),
    'getHandoffCountsByZip' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat))],
        ['query'],
      ),
    'getMarketplaceGeoJSON' : IDL.Func([], [IDL.Text], ['query']),
    'getPredictionEngineState' : IDL.Func(
        [],
        [PredictionEngineState],
        ['query'],
      ),
    'getRiskEvents' : IDL.Func([], [IDL.Vec(RiskEvent)], ['query']),
    'getSocialStressBaseline' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Float64))],
        [],
      ),
    'getTotalCostPlusReferrals' : IDL.Func([], [IDL.Nat], ['query']),
    'getTotalHandoffs' : IDL.Func([], [IDL.Nat], ['query']),
    'getTouchpointData' : IDL.Func([], [IDL.Vec(TouchpointRecord)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getWeatherAlerts' : IDL.Func([], [IDL.Text], []),
    'getWeatherRisk' : IDL.Func([], [IDL.Float64], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'receiveRiskPacket' : IDL.Func([RiskPacket], [], []),
    'recordCostPlusReferral' : IDL.Func([IDL.Text], [], []),
    'recordTouchpoint' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'registerHelper' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Bool,
          IDL.Text,
        ],
        [],
        [],
      ),
    'registerProvider' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Float64, IDL.Float64, IDL.Text],
        [],
        [],
      ),
    'removeRiskEvent' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'resetFiscalData' : IDL.Func([], [], []),
    'runHeartbeat' : IDL.Func([], [IDL.Vec(IDL.Text)], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setEmergencyActive' : IDL.Func([IDL.Bool], [], []),
    'setPredictionEngineState' : IDL.Func([PredictionEngineState], [], []),
    'setProviderActiveStatus' : IDL.Func([IDL.Text, IDL.Bool], [], []),
    'toggleLive' : IDL.Func([IDL.Text, IDL.Bool], [], []),
    'updateInventory' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'updateRiskEvent' : IDL.Func([IDL.Text, RiskEvent], [IDL.Bool], []),
    'verifyHandoff' : IDL.Func([IDL.Text], [VerifyResult], []),
    'verifyProvider' : IDL.Func([IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };