/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AdminSettings {
  'maintenanceModeEnabled' : boolean,
  'sentinelSensitivity' : string,
  'autoApproveProviders' : boolean,
  'emergencyBroadcastEnabled' : boolean,
  'emergencyBroadcastMessage' : string,
  'notifyOnNewProvider' : boolean,
  'notifyOnNewReport' : boolean,
  'notifyOnNewCredential' : boolean,
  'notifyOnNewVolunteer' : boolean,
}
export interface CanisterStateSummary {
  'active_providers' : Array<[string, bigint, boolean]>,
  'total_active_providers' : bigint,
  'high_risk_window_active' : boolean,
}
export interface CitizenReport {
  'id' : string,
  'lat' : [] | [number],
  'lng' : [] | [number],
  'upvotes' : bigint,
  'activityType' : string,
  'content' : string,
  'createdAt' : bigint,
  'zipCode' : string,
}
export interface Credential {
  'id' : bigint,
  'verifier' : [] | [Principal],
  'impactScore' : bigint,
  'badgeSvg' : [] | [string],
  'owner' : Principal,
  'metadata' : [] | [string],
  'name' : string,
  'credentialType' : CredentialType,
  'tier' : Tier,
  'description' : string,
  'cardMetadata' : [] | [string],
  'earnedAt' : bigint,
}
export type CredentialType = { 'BridgeProvider' : null } |
  { 'PolicyPioneer' : null } |
  { 'NarcanHero' : null } |
  { 'CommunityArchitect' : null } |
  { 'MATChampion' : null } |
  { 'RecoveryNavigator' : null } |
  { 'SentinelVerified' : null } |
  { 'CommunitySentinel' : null } |
  { 'StorySharer' : null } |
  { 'ThirtyDayGuide' : null } |
  { 'RecoveryAlly' : null } |
  { 'FirstResponder' : null };
export interface GlobalImpactStats {
  'totalImpactScore' : bigint,
  'activeContributors' : bigint,
  'totalBadgesMinted' : bigint,
}
export interface HarmReductionItem {
  'available' : boolean,
  'notes' : [] | [string],
  'itemType' : string,
  'quantity' : [] | [bigint],
}
export interface Helper {
  'id' : string,
  'zip' : string,
  'consent' : boolean,
  'note' : string,
  'createdAt' : bigint,
  'email' : string,
  'helpType' : string,
  'phone' : string,
  'lastName' : string,
  'firstName' : string,
}
export interface PredictionEngineState {
  'avgDailyHandoffCount' : bigint,
  'potencyToggle' : boolean,
  'sensitivitySlider' : bigint,
  'weatherToggle' : boolean,
  'simulationEnabled' : boolean,
  'stressToggle' : boolean,
  'paydayToggle' : boolean,
}
export interface ProfileUpdate {
  'bio' : [] | [string],
  'zip' : [] | [string],
  'displayName' : [] | [string],
  'city' : [] | [string],
  'role' : [] | [string],
  'privacyPublic' : [] | [boolean],
  'skills' : [] | [Array<string>],
}
export interface ProviderPost {
  'id' : string,
  'content' : string,
  'createdAt' : bigint,
  'imageUrl' : [] | [string],
  'providerId' : string,
}
export type ProviderStatus = { 'Live' : null } |
  { 'Offline' : null } |
  { 'Unknown' : null };
export interface ProviderWithStatus {
  'id' : string,
  'lat' : number,
  'lng' : number,
  'status' : ProviderStatus,
  'reputationScore' : bigint,
  'inventory' : string,
  'name' : string,
  'isLive' : boolean,
  'lastVerified' : bigint,
  'is_verified' : boolean,
  'providerType' : string,
  'is_active' : boolean,
}
export interface RecoveryProfile {
  'id' : string,
  'zip' : string,
  'resourcesUsed' : Array<string>,
  'displayName' : string,
  'createdAt' : bigint,
  'favoriteProviders' : Array<string>,
}
export type Result = { 'ok' : string } |
  { 'err' : string };
export interface RiskEvent {
  'id' : string,
  'multiplier' : number,
  'endDate' : bigint,
  'affectedZIPs' : Array<string>,
  'name' : string,
  'createdAt' : bigint,
  'startDate' : bigint,
  'fileUrl' : string,
}
export interface RiskPacket {
  'status' : boolean,
  'data_source' : string,
  'last_update_time' : bigint,
  'provider_id' : string,
  'risk_score' : bigint,
}
export interface Testimonial {
  'id' : string,
  'isApproved' : boolean,
  'content' : string,
  'authorId' : string,
  'createdAt' : bigint,
  'zipCode' : string,
  'isHidden' : boolean,
  'authorDisplayName' : string,
}
export type Tier = string;
export interface TouchpointRecord {
  'touchpoints' : bigint,
  'agentId' : string,
  'totalSaved' : number,
  'isStabilized' : boolean,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type VerifyResult = { 'Ok' : string } |
  { 'NotFound' : null } |
  { 'Expired' : null } |
  { 'AlreadyUsed' : null };
export interface VolunteerProfile {
  'id' : bigint,
  'bio' : string,
  'zip' : string,
  'principal' : [] | [Principal],
  'displayName' : string,
  'impactScore' : bigint,
  'city' : string,
  'joinedAt' : bigint,
  'role' : string,
  'privacyPublic' : boolean,
  'skills' : Array<string>,
}
export interface _SERVICE {
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'addFavoriteProvider' : ActorMethod<[string], boolean>,
  'addProviderPost' : ActorMethod<[string, string, [] | [string]], string>,
  'addRiskEvent' : ActorMethod<[RiskEvent], string>,
  'adminMintCredential' : ActorMethod<
    [Principal, CredentialType, [] | [string]],
    bigint
  >,
  /**
   * / Populates 18 demo credential records across all 12 types and 4 tiers.
   * / Guard: no-op if credentials already exist.
   * / Call once after fresh deploy to populate the leaderboard and gallery.
   */
  'adminSeedCredentials' : ActorMethod<[], string>,
  'approveTestimonial' : ActorMethod<[string], boolean>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'checkAndAutoMint' : ActorMethod<[Principal, string, bigint], undefined>,
  'createRecoveryProfile' : ActorMethod<[string, string], string>,
  'flagCitizenReport' : ActorMethod<[string], boolean>,
  'generateHandoffToken' : ActorMethod<[string], string>,
  'getActiveRiskBoosts' : ActorMethod<[], Array<[string, number]>>,
  'getAdminNotificationPrefs' : ActorMethod<
    [],
    {
      'notifyOnNewProvider' : boolean,
      'notifyOnNewReport' : boolean,
      'notifyOnNewCredential' : boolean,
      'notifyOnNewVolunteer' : boolean,
    }
  >,
  'getAdminSettings' : ActorMethod<[], AdminSettings>,
  'getAllHelpers' : ActorMethod<[], Array<Helper>>,
  'getAllProviders' : ActorMethod<[], Array<ProviderWithStatus>>,
  'getAllPublicBadges' : ActorMethod<[], Array<[Principal, bigint]>>,
  'getAllPublicVolunteers' : ActorMethod<[], Array<VolunteerProfile>>,
  'getAllReports' : ActorMethod<[], Array<CitizenReport>>,
  'getAllTestimonialsAdmin' : ActorMethod<[], Array<Testimonial>>,
  'getApprovedTestimonials' : ActorMethod<[], Array<Testimonial>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCanisterState' : ActorMethod<[], CanisterStateSummary>,
  'getCostPlusReferralCount' : ActorMethod<[string], bigint>,
  'getCredentialById' : ActorMethod<[bigint], [] | [Credential]>,
  'getEmergencyActive' : ActorMethod<[], Array<ProviderWithStatus>>,
  'getEmergencyBridgeStatus' : ActorMethod<
    [],
    { 'activatedAt' : bigint, 'activatedBy' : string, 'isActive' : boolean }
  >,
  'getFiscalData' : ActorMethod<
    [],
    {
      'communityReinvestmentFund' : number,
      'stabilityPipelinePercent' : number,
      'livesSaved' : number,
      'stabilizedAgents' : bigint,
      'touchpointCount' : bigint,
      'dollarsSaved' : number,
    }
  >,
  'getGlobalImpactStats' : ActorMethod<[], GlobalImpactStats>,
  'getHandoffCountsByZip' : ActorMethod<[], Array<[string, bigint]>>,
  'getHarmReductionInventory' : ActorMethod<[string], Array<HarmReductionItem>>,
  'getHelperCount' : ActorMethod<[], bigint>,
  'getMarketplaceGeoJSON' : ActorMethod<[], string>,
  'getPredictionEngineState' : ActorMethod<[], PredictionEngineState>,
  'getProviderPosts' : ActorMethod<[string], Array<ProviderPost>>,
  'getProvidersByHarmReductionItem' : ActorMethod<
    [string],
    Array<ProviderWithStatus>
  >,
  'getRecoveryProfile' : ActorMethod<[], [] | [RecoveryProfile]>,
  'getReportsByZip' : ActorMethod<[string], Array<CitizenReport>>,
  'getRiskEvents' : ActorMethod<[], Array<RiskEvent>>,
  'getSimulationStats' : ActorMethod<
    [],
    {
      'totalSimHandoffs' : bigint,
      'totalSimScans' : bigint,
      'totalSimVolunteers' : bigint,
      'simulationStartTime' : bigint,
    }
  >,
  'getSocialStressBaseline' : ActorMethod<[], Array<[string, number]>>,
  'getTestimonialCount' : ActorMethod<[], bigint>,
  'getTopContributors' : ActorMethod<
    [bigint],
    Array<[Principal, bigint, Array<string>]>
  >,
  'getTotalCostPlusReferrals' : ActorMethod<[], bigint>,
  'getTotalHandoffs' : ActorMethod<[], bigint>,
  'getTouchpointData' : ActorMethod<[], Array<TouchpointRecord>>,
  'getUserCredentials' : ActorMethod<[Principal], Array<Credential>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUserTimeline' : ActorMethod<[Principal], Array<Credential>>,
  'getVolunteer' : ActorMethod<[bigint], [] | [VolunteerProfile]>,
  'getVolunteerByPrincipal' : ActorMethod<[Principal], [] | [VolunteerProfile]>,
  'getWeatherAlerts' : ActorMethod<[], string>,
  'getWeatherRisk' : ActorMethod<[], number>,
  'hasCredential' : ActorMethod<[Principal, CredentialType], boolean>,
  'hideTestimonial' : ActorMethod<[string], boolean>,
  'incrementSimulationStats' : ActorMethod<[bigint, bigint], undefined>,
  'initSimulationTime' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'markResourceUsed' : ActorMethod<[string], boolean>,
  'mintCredential' : ActorMethod<
    [Principal, CredentialType, [] | [string], [] | [Principal]],
    bigint
  >,
  'receiveRiskPacket' : ActorMethod<[RiskPacket], undefined>,
  'recordCostPlusReferral' : ActorMethod<[string], undefined>,
  'recordTouchpoint' : ActorMethod<[string, string], undefined>,
  'registerHelper' : ActorMethod<
    [string, string, string, string, string, string, boolean, string],
    undefined
  >,
  'registerProvider' : ActorMethod<
    [string, string, number, number, string],
    undefined
  >,
  'registerVolunteerProfile' : ActorMethod<
    [string, string, string, string, string, Array<string>, boolean],
    bigint
  >,
  'removeFavoriteProvider' : ActorMethod<[string], boolean>,
  'removeRiskEvent' : ActorMethod<[string], boolean>,
  'resetFiscalData' : ActorMethod<[], undefined>,
  'runHeartbeat' : ActorMethod<[], Array<string>>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setEmergencyActive' : ActorMethod<[boolean], undefined>,
  'setHarmReductionInventory' : ActorMethod<
    [string, Array<HarmReductionItem>],
    undefined
  >,
  'setPredictionEngineState' : ActorMethod<[PredictionEngineState], undefined>,
  'setProviderActiveStatus' : ActorMethod<[string, boolean], undefined>,
  'setSimulationVolunteers' : ActorMethod<[bigint], undefined>,
  'storeTestimonial' : ActorMethod<[string, string, string], Result>,
  'submitCitizenReport' : ActorMethod<
    [string, string, string, [] | [number], [] | [number]],
    string
  >,
  'toggleLive' : ActorMethod<[string, boolean], undefined>,
  'updateAdminSettings' : ActorMethod<[AdminSettings], undefined>,
  'updateInventory' : ActorMethod<[string, string], undefined>,
  'updateRiskEvent' : ActorMethod<[string, RiskEvent], boolean>,
  'updateVolunteerProfile' : ActorMethod<[bigint, ProfileUpdate], boolean>,
  'upvoteCitizenReport' : ActorMethod<[string], boolean>,
  'verifyHandoff' : ActorMethod<[string], VerifyResult>,
  'verifyProvider' : ActorMethod<[string], undefined>,
  'volunteerCount' : ActorMethod<[], bigint>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];