/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type VerifyResult = {
    __kind__: "Ok";
    Ok: string;
} | {
    __kind__: "NotFound";
    NotFound: null;
} | {
    __kind__: "Expired";
    Expired: null;
} | {
    __kind__: "AlreadyUsed";
    AlreadyUsed: null;
};
export interface CitizenReport {
    id: string;
    lat?: number;
    lng?: number;
    upvotes: bigint;
    activityType: string;
    content: string;
    createdAt: bigint;
    zipCode: string;
}
export interface RiskEvent {
    id: string;
    multiplier: number;
    endDate: bigint;
    affectedZIPs: Array<string>;
    name: string;
    createdAt: bigint;
    startDate: bigint;
    fileUrl: string;
}
export interface ProviderWithStatus {
    id: string;
    lat: number;
    lng: number;
    status: ProviderStatus;
    reputationScore: bigint;
    inventory: string;
    name: string;
    isLive: boolean;
    lastVerified: bigint;
    is_verified: boolean;
    providerType: string;
    is_active: boolean;
}
export interface TouchpointRecord {
    touchpoints: bigint;
    agentId: string;
    totalSaved: number;
    isStabilized: boolean;
}
export interface RecoveryProfile {
    id: string;
    zip: string;
    resourcesUsed: Array<string>;
    displayName: string;
    createdAt: bigint;
    favoriteProviders: Array<string>;
}
export type Result = {
    __kind__: "ok";
    ok: string;
} | {
    __kind__: "err";
    err: string;
};
export interface RiskPacket {
    status: boolean;
    data_source: string;
    last_update_time: bigint;
    provider_id: string;
    risk_score: bigint;
}
export interface ProviderPost {
    id: string;
    content: string;
    createdAt: bigint;
    imageUrl?: string;
    providerId: string;
}
export interface CanisterStateSummary {
    active_providers: Array<[string, bigint, boolean]>;
    total_active_providers: bigint;
    high_risk_window_active: boolean;
}
export interface Helper {
    id: string;
    zip: string;
    consent: boolean;
    note: string;
    createdAt: bigint;
    email: string;
    helpType: string;
    phone: string;
    lastName: string;
    firstName: string;
}
export interface PredictionEngineState {
    avgDailyHandoffCount: bigint;
    potencyToggle: boolean;
    sensitivitySlider: bigint;
    weatherToggle: boolean;
    simulationEnabled: boolean;
    stressToggle: boolean;
    paydayToggle: boolean;
}
export interface HarmReductionItem {
    available: boolean;
    notes?: string;
    itemType: string;
    quantity?: bigint;
}
export interface UserProfile {
    name: string;
}
export interface Testimonial {
    id: string;
    isApproved: boolean;
    content: string;
    authorId: string;
    createdAt: bigint;
    zipCode: string;
    isHidden: boolean;
    authorDisplayName: string;
}
export enum ProviderStatus {
    Live = "Live",
    Offline = "Offline",
    Unknown = "Unknown"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControl(): Promise<void>;
    addFavoriteProvider(providerId: string): Promise<boolean>;
    addProviderPost(providerId: string, content: string, imageUrl: string | null): Promise<string>;
    addRiskEvent(event: RiskEvent): Promise<string>;
    approveTestimonial(id: string): Promise<boolean>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createRecoveryProfile(displayName: string, zip: string): Promise<string>;
    flagCitizenReport(id: string): Promise<boolean>;
    generateHandoffToken(zipCode: string): Promise<string>;
    getActiveRiskBoosts(): Promise<Array<[string, number]>>;
    getAllHelpers(): Promise<Array<Helper>>;
    getAllProviders(): Promise<Array<ProviderWithStatus>>;
    getAllReports(): Promise<Array<CitizenReport>>;
    getAllTestimonialsAdmin(): Promise<Array<Testimonial>>;
    getApprovedTestimonials(): Promise<Array<Testimonial>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCanisterState(): Promise<CanisterStateSummary>;
    getCostPlusReferralCount(providerId: string): Promise<bigint>;
    getEmergencyActive(): Promise<Array<ProviderWithStatus>>;
    getEmergencyBridgeStatus(): Promise<{
        activatedAt: bigint;
        activatedBy: string;
        isActive: boolean;
    }>;
    getFiscalData(): Promise<{
        communityReinvestmentFund: number;
        stabilityPipelinePercent: number;
        livesSaved: number;
        stabilizedAgents: bigint;
        touchpointCount: bigint;
        dollarsSaved: number;
    }>;
    getHandoffCountsByZip(): Promise<Array<[string, bigint]>>;
    getHarmReductionInventory(providerId: string): Promise<Array<HarmReductionItem>>;
    getHelperCount(): Promise<bigint>;
    getMarketplaceGeoJSON(): Promise<string>;
    getPredictionEngineState(): Promise<PredictionEngineState>;
    getProviderPosts(providerId: string): Promise<Array<ProviderPost>>;
    getProvidersByHarmReductionItem(itemType: string): Promise<Array<ProviderWithStatus>>;
    getRecoveryProfile(): Promise<RecoveryProfile | null>;
    getReportsByZip(zipCode: string): Promise<Array<CitizenReport>>;
    getRiskEvents(): Promise<Array<RiskEvent>>;
    getSimulationStats(): Promise<{
        totalSimHandoffs: bigint;
        totalSimScans: bigint;
        totalSimVolunteers: bigint;
        simulationStartTime: bigint;
    }>;
    getSocialStressBaseline(): Promise<Array<[string, number]>>;
    getTestimonialCount(): Promise<bigint>;
    getTotalCostPlusReferrals(): Promise<bigint>;
    getTotalHandoffs(): Promise<bigint>;
    getTouchpointData(): Promise<Array<TouchpointRecord>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getWeatherAlerts(): Promise<string>;
    getWeatherRisk(): Promise<number>;
    hideTestimonial(id: string): Promise<boolean>;
    incrementSimulationStats(handoffs: bigint, scans: bigint): Promise<void>;
    initSimulationTime(): Promise<void>;
    isCallerAdmin(): Promise<boolean>;
    markResourceUsed(resourceCategory: string): Promise<boolean>;
    receiveRiskPacket(packet: RiskPacket): Promise<void>;
    recordCostPlusReferral(providerId: string): Promise<void>;
    recordTouchpoint(agentId: string, _zip: string): Promise<void>;
    registerHelper(firstName: string, lastName: string, email: string, zip: string, phone: string, helpType: string, consent: boolean, note: string): Promise<void>;
    registerProvider(id: string, name: string, lat: number, lng: number, providerType: string): Promise<void>;
    removeFavoriteProvider(providerId: string): Promise<boolean>;
    removeRiskEvent(id: string): Promise<boolean>;
    resetFiscalData(): Promise<void>;
    runHeartbeat(): Promise<Array<string>>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    setEmergencyActive(isActive: boolean): Promise<void>;
    setHarmReductionInventory(providerId: string, items: Array<HarmReductionItem>): Promise<void>;
    setPredictionEngineState(state: PredictionEngineState): Promise<void>;
    setProviderActiveStatus(id: string, status: boolean): Promise<void>;
    setSimulationVolunteers(count: bigint): Promise<void>;
    storeTestimonial(displayName: string, zipCode: string, content: string): Promise<Result>;
    submitCitizenReport(zipCode: string, activityType: string, content: string, lat: number | null, lng: number | null): Promise<string>;
    toggleLive(id: string, status: boolean): Promise<void>;
    updateInventory(id: string, newInventory: string): Promise<void>;
    updateRiskEvent(id: string, event: RiskEvent): Promise<boolean>;
    upvoteCitizenReport(reportId: string): Promise<boolean>;
    verifyHandoff(token: string): Promise<VerifyResult>;
    verifyProvider(id: string): Promise<void>;
}
import type { CitizenReport as _CitizenReport, HarmReductionItem as _HarmReductionItem, ProviderPost as _ProviderPost, ProviderStatus as _ProviderStatus, ProviderWithStatus as _ProviderWithStatus, RecoveryProfile as _RecoveryProfile, Result as _Result, UserProfile as _UserProfile, UserRole as _UserRole, VerifyResult as _VerifyResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControl();
            return result;
        }
    }
    async addFavoriteProvider(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.addFavoriteProvider(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addFavoriteProvider(arg0);
            return result;
        }
    }
    async addProviderPost(arg0: string, arg1: string, arg2: string | null): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.addProviderPost(arg0, arg1, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addProviderPost(arg0, arg1, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async addRiskEvent(arg0: RiskEvent): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.addRiskEvent(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addRiskEvent(arg0);
            return result;
        }
    }
    async approveTestimonial(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.approveTestimonial(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.approveTestimonial(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n2(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n2(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createRecoveryProfile(arg0: string, arg1: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createRecoveryProfile(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createRecoveryProfile(arg0, arg1);
            return result;
        }
    }
    async flagCitizenReport(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.flagCitizenReport(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.flagCitizenReport(arg0);
            return result;
        }
    }
    async generateHandoffToken(arg0: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.generateHandoffToken(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.generateHandoffToken(arg0);
            return result;
        }
    }
    async getActiveRiskBoosts(): Promise<Array<[string, number]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getActiveRiskBoosts();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getActiveRiskBoosts();
            return result;
        }
    }
    async getAllHelpers(): Promise<Array<Helper>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllHelpers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllHelpers();
            return result;
        }
    }
    async getAllProviders(): Promise<Array<ProviderWithStatus>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllProviders();
                return from_candid_vec_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllProviders();
            return from_candid_vec_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllReports(): Promise<Array<CitizenReport>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllReports();
                return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllReports();
            return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllTestimonialsAdmin(): Promise<Array<Testimonial>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllTestimonialsAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllTestimonialsAdmin();
            return result;
        }
    }
    async getApprovedTestimonials(): Promise<Array<Testimonial>> {
        if (this.processError) {
            try {
                const result = await this.actor.getApprovedTestimonials();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getApprovedTestimonials();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCanisterState(): Promise<CanisterStateSummary> {
        if (this.processError) {
            try {
                const result = await this.actor.getCanisterState();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCanisterState();
            return result;
        }
    }
    async getCostPlusReferralCount(arg0: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getCostPlusReferralCount(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCostPlusReferralCount(arg0);
            return result;
        }
    }
    async getEmergencyActive(): Promise<Array<ProviderWithStatus>> {
        if (this.processError) {
            try {
                const result = await this.actor.getEmergencyActive();
                return from_candid_vec_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEmergencyActive();
            return from_candid_vec_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async getEmergencyBridgeStatus(): Promise<{
        activatedAt: bigint;
        activatedBy: string;
        isActive: boolean;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getEmergencyBridgeStatus();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEmergencyBridgeStatus();
            return result;
        }
    }
    async getFiscalData(): Promise<{
        communityReinvestmentFund: number;
        stabilityPipelinePercent: number;
        livesSaved: number;
        stabilizedAgents: bigint;
        touchpointCount: bigint;
        dollarsSaved: number;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getFiscalData();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFiscalData();
            return result;
        }
    }
    async getHandoffCountsByZip(): Promise<Array<[string, bigint]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getHandoffCountsByZip();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getHandoffCountsByZip();
            return result;
        }
    }
    async getHarmReductionInventory(arg0: string): Promise<Array<HarmReductionItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.getHarmReductionInventory(arg0);
                return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getHarmReductionInventory(arg0);
            return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getHelperCount(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getHelperCount();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getHelperCount();
            return result;
        }
    }
    async getMarketplaceGeoJSON(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getMarketplaceGeoJSON();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMarketplaceGeoJSON();
            return result;
        }
    }
    async getPredictionEngineState(): Promise<PredictionEngineState> {
        if (this.processError) {
            try {
                const result = await this.actor.getPredictionEngineState();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPredictionEngineState();
            return result;
        }
    }
    async getProviderPosts(arg0: string): Promise<Array<ProviderPost>> {
        if (this.processError) {
            try {
                const result = await this.actor.getProviderPosts(arg0);
                return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProviderPosts(arg0);
            return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProvidersByHarmReductionItem(arg0: string): Promise<Array<ProviderWithStatus>> {
        if (this.processError) {
            try {
                const result = await this.actor.getProvidersByHarmReductionItem(arg0);
                return from_candid_vec_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProvidersByHarmReductionItem(arg0);
            return from_candid_vec_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRecoveryProfile(): Promise<RecoveryProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getRecoveryProfile();
                return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRecoveryProfile();
            return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getReportsByZip(arg0: string): Promise<Array<CitizenReport>> {
        if (this.processError) {
            try {
                const result = await this.actor.getReportsByZip(arg0);
                return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReportsByZip(arg0);
            return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRiskEvents(): Promise<Array<RiskEvent>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRiskEvents();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRiskEvents();
            return result;
        }
    }
    async getSimulationStats(): Promise<{
        totalSimHandoffs: bigint;
        totalSimScans: bigint;
        totalSimVolunteers: bigint;
        simulationStartTime: bigint;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getSimulationStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSimulationStats();
            return result;
        }
    }
    async getSocialStressBaseline(): Promise<Array<[string, number]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSocialStressBaseline();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSocialStressBaseline();
            return result;
        }
    }
    async getTestimonialCount(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getTestimonialCount();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTestimonialCount();
            return result;
        }
    }
    async getTotalCostPlusReferrals(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getTotalCostPlusReferrals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTotalCostPlusReferrals();
            return result;
        }
    }
    async getTotalHandoffs(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getTotalHandoffs();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTotalHandoffs();
            return result;
        }
    }
    async getTouchpointData(): Promise<Array<TouchpointRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTouchpointData();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTouchpointData();
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getWeatherAlerts(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getWeatherAlerts();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWeatherAlerts();
            return result;
        }
    }
    async getWeatherRisk(): Promise<number> {
        if (this.processError) {
            try {
                const result = await this.actor.getWeatherRisk();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWeatherRisk();
            return result;
        }
    }
    async hideTestimonial(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.hideTestimonial(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.hideTestimonial(arg0);
            return result;
        }
    }
    async incrementSimulationStats(arg0: bigint, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.incrementSimulationStats(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.incrementSimulationStats(arg0, arg1);
            return result;
        }
    }
    async initSimulationTime(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.initSimulationTime();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initSimulationTime();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async markResourceUsed(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.markResourceUsed(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markResourceUsed(arg0);
            return result;
        }
    }
    async receiveRiskPacket(arg0: RiskPacket): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.receiveRiskPacket(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.receiveRiskPacket(arg0);
            return result;
        }
    }
    async recordCostPlusReferral(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.recordCostPlusReferral(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordCostPlusReferral(arg0);
            return result;
        }
    }
    async recordTouchpoint(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.recordTouchpoint(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordTouchpoint(arg0, arg1);
            return result;
        }
    }
    async registerHelper(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string, arg5: string, arg6: boolean, arg7: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.registerHelper(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerHelper(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
            return result;
        }
    }
    async registerProvider(arg0: string, arg1: string, arg2: number, arg3: number, arg4: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.registerProvider(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerProvider(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async removeFavoriteProvider(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.removeFavoriteProvider(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeFavoriteProvider(arg0);
            return result;
        }
    }
    async removeRiskEvent(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.removeRiskEvent(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeRiskEvent(arg0);
            return result;
        }
    }
    async resetFiscalData(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.resetFiscalData();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.resetFiscalData();
            return result;
        }
    }
    async runHeartbeat(): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.runHeartbeat();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.runHeartbeat();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async setEmergencyActive(arg0: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setEmergencyActive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setEmergencyActive(arg0);
            return result;
        }
    }
    async setHarmReductionInventory(arg0: string, arg1: Array<HarmReductionItem>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setHarmReductionInventory(arg0, to_candid_vec_n25(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setHarmReductionInventory(arg0, to_candid_vec_n25(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async setPredictionEngineState(arg0: PredictionEngineState): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setPredictionEngineState(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setPredictionEngineState(arg0);
            return result;
        }
    }
    async setProviderActiveStatus(arg0: string, arg1: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setProviderActiveStatus(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setProviderActiveStatus(arg0, arg1);
            return result;
        }
    }
    async setSimulationVolunteers(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setSimulationVolunteers(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setSimulationVolunteers(arg0);
            return result;
        }
    }
    async storeTestimonial(arg0: string, arg1: string, arg2: string): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.storeTestimonial(arg0, arg1, arg2);
                return from_candid_Result_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.storeTestimonial(arg0, arg1, arg2);
            return from_candid_Result_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async submitCitizenReport(arg0: string, arg1: string, arg2: string, arg3: number | null, arg4: number | null): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.submitCitizenReport(arg0, arg1, arg2, to_candid_opt_n30(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n30(this._uploadFile, this._downloadFile, arg4));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitCitizenReport(arg0, arg1, arg2, to_candid_opt_n30(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n30(this._uploadFile, this._downloadFile, arg4));
            return result;
        }
    }
    async toggleLive(arg0: string, arg1: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.toggleLive(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.toggleLive(arg0, arg1);
            return result;
        }
    }
    async updateInventory(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateInventory(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateInventory(arg0, arg1);
            return result;
        }
    }
    async updateRiskEvent(arg0: string, arg1: RiskEvent): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateRiskEvent(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateRiskEvent(arg0, arg1);
            return result;
        }
    }
    async upvoteCitizenReport(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.upvoteCitizenReport(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.upvoteCitizenReport(arg0);
            return result;
        }
    }
    async verifyHandoff(arg0: string): Promise<VerifyResult> {
        if (this.processError) {
            try {
                const result = await this.actor.verifyHandoff(arg0);
                return from_candid_VerifyResult_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.verifyHandoff(arg0);
            return from_candid_VerifyResult_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async verifyProvider(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.verifyProvider(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.verifyProvider(arg0);
            return result;
        }
    }
}
function from_candid_CitizenReport_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CitizenReport): CitizenReport {
    return from_candid_record_n11(_uploadFile, _downloadFile, value);
}
function from_candid_HarmReductionItem_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _HarmReductionItem): HarmReductionItem {
    return from_candid_record_n18(_uploadFile, _downloadFile, value);
}
function from_candid_ProviderPost_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ProviderPost): ProviderPost {
    return from_candid_record_n23(_uploadFile, _downloadFile, value);
}
function from_candid_ProviderStatus_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ProviderStatus): ProviderStatus {
    return from_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function from_candid_ProviderWithStatus_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ProviderWithStatus): ProviderWithStatus {
    return from_candid_record_n6(_uploadFile, _downloadFile, value);
}
function from_candid_Result_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result): Result {
    return from_candid_variant_n29(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function from_candid_VerifyResult_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _VerifyResult): VerifyResult {
    return from_candid_variant_n32(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [number]): number | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_RecoveryProfile]): RecoveryProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    lat: [] | [number];
    lng: [] | [number];
    upvotes: bigint;
    activityType: string;
    content: string;
    createdAt: bigint;
    zipCode: string;
}): {
    id: string;
    lat?: number;
    lng?: number;
    upvotes: bigint;
    activityType: string;
    content: string;
    createdAt: bigint;
    zipCode: string;
} {
    return {
        id: value.id,
        lat: record_opt_to_undefined(from_candid_opt_n12(_uploadFile, _downloadFile, value.lat)),
        lng: record_opt_to_undefined(from_candid_opt_n12(_uploadFile, _downloadFile, value.lng)),
        upvotes: value.upvotes,
        activityType: value.activityType,
        content: value.content,
        createdAt: value.createdAt,
        zipCode: value.zipCode
    };
}
function from_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    available: boolean;
    notes: [] | [string];
    itemType: string;
    quantity: [] | [bigint];
}): {
    available: boolean;
    notes?: string;
    itemType: string;
    quantity?: bigint;
} {
    return {
        available: value.available,
        notes: record_opt_to_undefined(from_candid_opt_n19(_uploadFile, _downloadFile, value.notes)),
        itemType: value.itemType,
        quantity: record_opt_to_undefined(from_candid_opt_n20(_uploadFile, _downloadFile, value.quantity))
    };
}
function from_candid_record_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    content: string;
    createdAt: bigint;
    imageUrl: [] | [string];
    providerId: string;
}): {
    id: string;
    content: string;
    createdAt: bigint;
    imageUrl?: string;
    providerId: string;
} {
    return {
        id: value.id,
        content: value.content,
        createdAt: value.createdAt,
        imageUrl: record_opt_to_undefined(from_candid_opt_n19(_uploadFile, _downloadFile, value.imageUrl)),
        providerId: value.providerId
    };
}
function from_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    lat: number;
    lng: number;
    status: _ProviderStatus;
    reputationScore: bigint;
    inventory: string;
    name: string;
    isLive: boolean;
    lastVerified: bigint;
    is_verified: boolean;
    providerType: string;
    is_active: boolean;
}): {
    id: string;
    lat: number;
    lng: number;
    status: ProviderStatus;
    reputationScore: bigint;
    inventory: string;
    name: string;
    isLive: boolean;
    lastVerified: bigint;
    is_verified: boolean;
    providerType: string;
    is_active: boolean;
} {
    return {
        id: value.id,
        lat: value.lat,
        lng: value.lng,
        status: from_candid_ProviderStatus_n7(_uploadFile, _downloadFile, value.status),
        reputationScore: value.reputationScore,
        inventory: value.inventory,
        name: value.name,
        isLive: value.isLive,
        lastVerified: value.lastVerified,
        is_verified: value.is_verified,
        providerType: value.providerType,
        is_active: value.is_active
    };
}
function from_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: string;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: string;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Ok: string;
} | {
    NotFound: null;
} | {
    Expired: null;
} | {
    AlreadyUsed: null;
}): {
    __kind__: "Ok";
    Ok: string;
} | {
    __kind__: "NotFound";
    NotFound: null;
} | {
    __kind__: "Expired";
    Expired: null;
} | {
    __kind__: "AlreadyUsed";
    AlreadyUsed: null;
} {
    return "Ok" in value ? {
        __kind__: "Ok",
        Ok: value.Ok
    } : "NotFound" in value ? {
        __kind__: "NotFound",
        NotFound: value.NotFound
    } : "Expired" in value ? {
        __kind__: "Expired",
        Expired: value.Expired
    } : "AlreadyUsed" in value ? {
        __kind__: "AlreadyUsed",
        AlreadyUsed: value.AlreadyUsed
    } : value;
}
function from_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Live: null;
} | {
    Offline: null;
} | {
    Unknown: null;
}): ProviderStatus {
    return "Live" in value ? ProviderStatus.Live : "Offline" in value ? ProviderStatus.Offline : "Unknown" in value ? ProviderStatus.Unknown : value;
}
function from_candid_vec_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_HarmReductionItem>): Array<HarmReductionItem> {
    return value.map((x)=>from_candid_HarmReductionItem_n17(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ProviderPost>): Array<ProviderPost> {
    return value.map((x)=>from_candid_ProviderPost_n22(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ProviderWithStatus>): Array<ProviderWithStatus> {
    return value.map((x)=>from_candid_ProviderWithStatus_n5(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_CitizenReport>): Array<CitizenReport> {
    return value.map((x)=>from_candid_CitizenReport_n10(_uploadFile, _downloadFile, x));
}
function to_candid_HarmReductionItem_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: HarmReductionItem): _HarmReductionItem {
    return to_candid_record_n27(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: number | null): [] | [number] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    available: boolean;
    notes?: string;
    itemType: string;
    quantity?: bigint;
}): {
    available: boolean;
    notes: [] | [string];
    itemType: string;
    quantity: [] | [bigint];
} {
    return {
        available: value.available,
        notes: value.notes ? candid_some(value.notes) : candid_none(),
        itemType: value.itemType,
        quantity: value.quantity ? candid_some(value.quantity) : candid_none()
    };
}
function to_candid_variant_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_vec_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<HarmReductionItem>): Array<_HarmReductionItem> {
    return value.map((x)=>to_candid_HarmReductionItem_n26(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
